name: build-nanogpt
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - numpy
      - transformers
      - datasets
      - tiktoken
      - tqdm
      - wandb


